name: Hello World
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Say-Hello-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello 
        run: echo "Hello World"
